[package]
name = "sa6"
version = "0.1.0"
edition = "2021"




[dependencies]
chrono = { version="0.4.34", features=["serde"]}
actix-web = "4"
diesel = { version = "2.1.0", features = ["mysql","chrono"] }
dotenvy = "0.15"
serde = "1.0.197"
mysql = "24.0.0"
actix-rt = "2.9.0"
actix-cors = "0.7.0"
